## NumPy Array

In [3]:
import numpy as np

A = np.array([1, 2, 3, 4])

In [5]:
# NumPy will upcast to same type if possible
B = np.array([1.1, 2.2, 3.3, 4])
print(B.dtype)
print(B)

float64
[1.1 2.2 3.3 4. ]


In [6]:
# Set data type explicitly
C = np.array([1.1, 2.2, 3.3, 4], dtype='float64')

In [8]:
# Multi dimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
# Built in routines in NumPy to create large arrays

# Create an array of zeros
np.zeros(10, dtype=int)

# 3x5 floating point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# create a 3x3 array of random values between 0 and 1
np.random.random((3, 3))

array([[0.08542318, 0.24210387, 0.64525679],
       [0.77303673, 0.4516207 , 0.26967577],
       [0.60975502, 0.20864957, 0.23069925]])

In [14]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.65306593, -2.07522705,  0.59655359],
       [-1.3503301 ,  0.98845861, -0.22261834],
       [-0.27250041, -0.25525656,  1.13527845]])

In [15]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 0, 7],
       [2, 1, 6],
       [0, 0, 2]])

In [16]:
# create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

### Standard data types in numPy

![Standard data types](./assets/dataTypes.png)