### NumPy Array Attributes

In [3]:
import numpy as np 
np.random.seed(0)  # Seed for reproducibility

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64
x3 itemsize:  8 bytes
x3 nbytes:  480 bytes


### Array Indexing

In [5]:
x1 = np.array([4, 3, 4, 4, 8, 7])

print(x1[0])   # First element
print(x1[-1])  # Last element
print(x1[-3])  # Third from the end

# In numPy arrays, type is fixed, so if you attempt to insert a floating-point value to an integer array,
# the value will be silently truncated.

4
7
4


### Array Slicing
<pre>
x[start:stop:step]
</pre>
default -> start = 0, stop = size of dimension, step = 1

In [14]:
x = np.array([1, 2, 3, 4, 5])

print(x[2:5])  # Elements 2-4
print(x[::2])  # Every other element
print(x[1::2])  # Every other element, starting at index 1
print(x[::-1])  # All elements, reversed, start and end are swapped

[3 4 5]
[1 3 5]
[2 4]
[5 4 3 2 1]


In [17]:
x2 = np.array([range(i, i + 3) for i in [1, 4, 7]])

print(x2)
print(x2[:2, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


### Accessing rows and columns

In [20]:
print(x2[:, 0]) # First column of x2

print(x2[0, :]) # First row of x2
# or
print(x2[0])

[1 4 7]
[1 2 3]
[1 2 3]
