### Reshaping of arrays

In [3]:
import numpy as np

grid = np.arange(1, 10).reshape((3, 3))  # 3x3 grid
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# convert a list to row/column matrix
rowM = np.arange(1, 6).reshape((1, 5))
print(rowM)
colM = np.arange(1, 6).reshape((5, 1))
print(colM)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### Array Concatenation

In [6]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])  # concatenate 1D arrays

array([1, 2, 3, 4, 5, 6])

In [7]:
z = np.array([7, 8, 9])
np.concatenate([x, y, z])  # concatenate 1D arrays

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.concatenate([grid, grid])  # concatenate 2D arrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.concatenate([grid, grid], axis = 1)  # concatenate 2D arrays

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [10]:
x2 = np.array([1, 2, 3])
grid2 = np.array([[9, 8, 7], 
                  [6, 5, 4]])
np.vstack([x2, grid2])  # vertically stack arrays

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [11]:
y2 = np.array([[99],
               [99]])
np.hstack([grid2, y2])  # horizontally

# similarly, np.dstack will stack arrays along the third axis

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [12]:
x3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1, s2, s3 = np.split(x3, [3, 5])  # split at index 3 and 5
print(s1, s2, s3)

[1 2 3] [4 5] [6 7 8 9]


In [13]:
upper, lower = np.vsplit(grid, [2])  # split at row index 2
print(upper)
print(lower)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [14]:
left, right = np.hsplit(grid, [2])  # split at column index 2
print(left)
print(right)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]
