### Trigonometrix functions

In [3]:
import numpy as np
np.random.seed(0)

theta = np.linspace(0, np.pi, 3)
print("theta: ", theta)
print("sin(theta): ", np.sin(theta))
print("cos(theta): ", np.cos(theta))
print("tan(theta): ", np.tan(theta))

print("Inverse sin: ", np.arcsin(np.sin(theta)))
print("Inverse cos: ", np.arccos(np.cos(theta)))
print("Inverse tan: ", np.arctan(np.tan(theta)))

theta:  [0.         1.57079633 3.14159265]
sin(theta):  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta):  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta):  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Inverse sin:  [0.00000000e+00 1.57079633e+00 1.22464680e-16]
Inverse cos:  [0.         1.57079633 3.14159265]
Inverse tan:  [ 0.00000000e+00  1.57079633e+00 -1.22464680e-16]


### Exponents and Logarithms

In [4]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [5]:
print("log(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

log(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


In [6]:
print("exp(x) - 1: ", np.expm1(x))
print("Log(1 + x): ", np.log1p(x))

exp(x) - 1:  [ 1.71828183  6.3890561  19.08553692]
Log(1 + x):  [0.69314718 1.09861229 1.38629436]


### Aggregates

In [11]:
x = np.arange(5)
print(x)
print(np.add.reduce(x))

np.add.accumulate(x)

[0 1 2 3 4]
10


array([ 0,  1,  3,  6, 10])

In [13]:
m = np.random.random((3, 4))
print(m.max(axis=0))  # max of each column
print(m.max(axis=1))  # max of each row

# axis keyword specifies the dimension of the array that will be collapsed

[0.97861834 0.92559664 0.77815675 0.87001215]
[0.07103606 0.0202184  0.46147936]


![Aggregation functions of numPy](./assets/agg.png)