## Broadcasting

- Broadcasting allows binary operations to be performed on arrays of different sizes

In [2]:
import numpy as np

a = np.array([i for i in range(3)])
print(a)
a + 5

[0 1 2]


array([5, 6, 7])

- We can think of this as an operation that stretches or duplicates the value 5 into the
array [5, 5, 5], and adds the results.

In [8]:
m = np.array([range(i, i + 3) for i in [1, 4, 7]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
m + a

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

- one-dimensional array a is stretched, or broadcast, across the second
dimension in order to match the shape of M.

In [13]:
b = np.arange(3)
c = np.arange(3)[:, np.newaxis]
print(b)
print(c)

[0 1 2]
[[0]
 [1]
 [2]]


In [14]:
print(b + c)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


- Just as before we stretched or broadcasted one value to match the shape of the other,
here we’ve stretched both a and b to match a common shape, and the result is a two-
dimensional array!
![Broadcasting](./assets/broadcasting.png)

### Rules of broadcasting
- <b>Rule 1 :</b> If two arrays differ in their number of dimensions, the one with fewer dimensions will be padded with 1s on its leading (left) side
- <b>Rule 2 :</b> If the shape of the two arrays does not match in any dimension, he array with shape = 1 in that dimension is stretched to match the other shape.
- <b>Rule 3 :</b> If in any dimenstion, the sizes disagree and neither is equal to 1, an error is raised.

### Braodcasting example 1

In [3]:
m = np.ones((2, 3))
a = np.arange(3)
print(m)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


- Lets consider an operation on these two arrays.
<pre>
    m.shape = (2, 3)
    a.shape = (3, )
</pre>

- By rule 1, a has fewer dimensions, so we pad it on the left with 1s.
<pre>
    m.shape -> (2, 3)
    a.shape -> (1, 3)
</pre>

- By rule 2, now we see that the first dimension disagrees, so we stretch this dimension to match:
<pre>
    m.shape -> (2, 3)
    a.shape -> (2, 3)
</pre>

- The shapes match, and we see that the final shape will be (2, 3)

In [4]:
m + a

array([[1., 2., 3.],
       [1., 2., 3.]])

### Broadcasting example 2

In [6]:
a2 = np.arange(3).reshape((3, 1))
b2 = np.arange(3)
print(a2)
print(b2)

[[0]
 [1]
 [2]]
[0 1 2]


- shape of the arrays:
<pre>
    a2.shape = (3, 1)
    b2.shape = (3, )
</pre>

- Rule 1 says we must pad the shape of b2 with 1s.
<pre>
    a2.shape -> (3, 1)
    b2.shape -> (1, 3)
</pre>

- And rule 2 says we must upgrade each of these ones to match the corresponding size of the other array.
<pre>
    a2.shape -> (3, 3)
    b2.shape -> (3, 3)

- Because the result matches, these shapes are compatible.

In [7]:
a2 + b2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])