## Comparisons

- NumPy also implements comparison operators such as < (less than) and > (greater than) as element-wise ufuncs.
- The result of these comparison operators is always an array with a Boolean data type.

In [2]:
import numpy as np

x = np.array([1, 2, 3])
x < 3

array([ True,  True, False])

In [3]:
# Element-wise comparison between two arrays
(2 ** x) == (x ** 2)

array([False,  True, False])

- Comparison operators are implemented as ufuncs in numPy

    ![Comparison operators and their corresponding ufuncs](./assets/comparisons.png)

## Boolean Arrays

In [4]:
rng = np.random.RandomState(0)    # seed = 0
x = rng.randint(10, size=(3, 4))  # random no. between 0 and 10
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [8]:
# Counting no. of entries
print(np.count_nonzero(x < 6))
# OR
print(np.sum(x < 6))

8
8


In [9]:
# no. of entries less than 6 in each row
print(np.sum(x < 6, axis=1))

[4 2 2]


In [10]:
# Are all values less than 6?
np.all(x < 6)

np.False_

In [11]:
# Are any values less than 6?
np.any(x < 6)

np.True_

In [12]:
# Are all values less than 8 in each row?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [13]:
# count values greater than 5 and less than 8
np.sum((x > 5) & (x < 8))

np.int64(3)

![Bitwise operators and their corresp. ufuncs](./assets/bitwiseOps.png)

## Boolean arrays as masks

- suppose we want an array of all values in the array that are less than, say, 5.
- We can obtain a Boolean array for this condition easily, as we’ve already seen:

In [15]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

- Now to <b>select</b> these values from the array, we can simply index on this Boolean array;
this is known as a masking operation:
- What is returned is a one-dimensional array filled with all the values that meet this
condition; in other words, all the values in positions at which the mask array is True.

In [16]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])