## Fancy indexing

In [2]:
import numpy as np 
random = np.random.RandomState(42)

x = random.randint(100, size=10)
print(x)


[51 92 14 71 60 20 82 86 74 74]


In [3]:
# To access three different elements
print(x[0], x[3], x[7])

51 71 86


In [5]:
# or else, using fancy indexing
ind = [0, 3, 7]
x[ind]

array([51, 71, 86])

- With fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed:

In [6]:
ind = np.array([[3, 7], [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [10]:
# Fancy indexing also works in multiple dimensions

X = np.arange(12).reshape((3, 4))
print(X)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 2,  5, 11])