## Sorting

In [2]:
import numpy as np 
x = np.array([3, 5, 7, 8, 1, 3])
np.sort(x)

array([1, 3, 3, 5, 7, 8])

In [3]:
# to sort in place, use the sort method of arrays
x.sort()
print(x)

[1 3 3 5 7 8]


In [5]:
# argsort returns indices of sorted elements
# first element gives the index of the smallest element
# second element gives the index of the second smallest element, and so on
x = np.array([3, 5, 7, 8, 1, 3])
i = np.argsort(x)
print(i)

[4 0 5 1 2 3]


### Sorting along rows and columns

In [6]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [7]:
# sort each column of X
print(np.sort(X, axis=0))

[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]


In [8]:
# sort each row of X
print(np.sort(X, axis=1))

[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


### Partial Sorts: Partitioning

- Sometimes we’re not interested in sorting the entire array, but simply want to find the
K smallest values in the array
- NumPy provides this in the `np.partition function`. `np.partition` takes an array and a number K;
- result is a new array with the smallest K values to the left of the partition, and the remaining values to the right, in arbitrary order

In [9]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
print(np.partition(x, 3))

[1 2 3 4 5 6 7]


In [10]:
# we can partition along an arbitrary axis of a multidimensional array:
# result is an array where the first two slots in each row contain the smallest values from that row
print(np.partition(X, 2, axis=1))

[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]
